require ("core.plugin_config.gruvbox")
require ("core.plugin_config.nvim_tree")
require ("core.plugin_config.telescope")
require ("core.plugin_config.treesitter")
require ("core.plugin_config.nvim_web_devicons")
require ("core.plugin_config.code_completion")
require ("core.plugin_config.lsp")
require ("core.plugin_config.git_config")
require ("core.plugin_config.lualine")
require ("core.plugin_config.comment")
require ("core.plugin_config.dashboard")
-- require ("core.plugin_config.noice")
require ("core.plugin_config.whichkey")

